### ISSUE TITLE
netconnectd.service file not found

### ISSUE THREAD

**Issue by chsims1** [foosel/netconnectd#14]

**Comment by cbandera** [comment]
I just had the same problem and was searching for the cause quite a while...
The solution is simple:
The error message says "I don't know any service called netconnectd"
This is because we haven't registered the service yet.
To fix this run:

    sudo update-rc.d netconnectd

After this you can start the service

    sudo service netconnectd start

**Comment by marianoronchi** [comment]
sudo update-rc.d netconnectd defaults 80
Worked for me in RPi3

**Comment by nargetdev** [comment]
Can verify that the above ^^ fixes the issue that the service didn't start.

**Comment by foosel** [comment]
And it's been in the README since always ;)

At the wrong location though. Fixed.
