### ISSUE TITLE
Disable automatic AP start on no network?

### ISSUE THREAD

**Issue by jminardi** [foosel/netconnectd#9]
I know that functionality is one of the main reasons netconnectd exists, but in my usecase I would much rather manually control when the AP is started and stopped.

Is it possible to disable the automatic launch of the AP?

**Comment by foosel** [comment]
Nope. It's actually also not one of but *the* main reason. If you need that functionality, feel free to add it as a configurable flag, I'd happily accept a PR, but to be quite honest I don't see the point in using netconnectd in such a usage scenario, network connectivity management without ap fallback is provided by many packages out there already.

**Comment by jminardi** [comment]
netconnectd is one of the easiest methods of managing wifi connectivity from the commandline, and I like that it makes it dead simple to launch an AP.

I will look into adding a configuration flag to disable auto AP mode.

**Comment by jminardi** [comment]
If I don't add a timeout to `/etc/dhcp/dhclient.conf` would that have the same effect of disabling automatic AP starting?

**Comment by foosel** [comment]
If I remember correctly, that would actually make everything just hang since the ifup command would never return.

**Comment by jminardi** [comment]
Ok makes sense.

I thought I remembered seeing somewhere to configure the URL netconnectd hits to check for connectivity, but I don't see that anywhere in the config. If I could change that to localhost then it would always think it is connected and not need to start an AP, right?

**Comment by foosel** [comment]
It doesn't ping, it checks with `ip neigh show` if it can see any other hosts: https://github.com/foosel/netconnectd/blob/master/netconnectd/util.py#L18

Wouldn't make much sense to ping an external ip (user might want to connect to a Wi-Fi that is local online or heavily filtered) and making assumptions about ips that should be reachable just screams for trouble, hence the ip neighborhood approach.

**Comment by jminardi** [comment]
Ok, with that being the case I don't think I need this behavior. I was under the impression that an AP would be started if the printer didn't have connection to the greater internet, not just any network.

Closing this now.
